<?php

declare(strict_types=1);

namespace Rkn\Cms\Cli;

use Rkn\Cms\Content\Indexer;
use Rkn\Cms\Mcp\Tools\ListComponentsTool;
use Rkn\Cms\Mcp\Tools\ListTemplatesTool;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Yaml\Yaml;

#[AsCommand(name: 'boost:install', description: 'Generate CLAUDE.md and .mcp.json for AI integration')]
final class BoostInstallCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $basePath = $this->findBasePath();
        $generated = [];

        // Generate CLAUDE.md
        $claudeMd = $this->generateClaudeMd($basePath);
        file_put_contents($basePath . '/CLAUDE.md', $claudeMd);
        $generated[] = 'CLAUDE.md';

        // Generate .mcp.json
        $mcpJson = $this->generateMcpJson();
        file_put_contents($basePath . '/.mcp.json', json_encode($mcpJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
        $generated[] = '.mcp.json';

        $output->writeln('<info>Boost installed successfully!</info>');
        foreach ($generated as $file) {
            $output->writeln("  Generated: {$file}");
        }

        return Command::SUCCESS;
    }

    private function generateClaudeMd(string $basePath): string
    {
        $lines = ["# CLAUDE.md\n"];
        $lines[] = "Auto-generated by `rakun boost:install`. Provides AI context for this project.\n";

        // Project name from config
        $projectName = 'RakunCMS Project';
        $configFile = $basePath . '/config/rakun.yaml';
        if (file_exists($configFile)) {
            $config = Yaml::parseFile($configFile);
            $projectName = $config['site']['name'] ?? $config['site']['url'] ?? $projectName;
        }
        $lines[] = "## Project: {$projectName}\n";

        // Collections
        $lines[] = "## Collections\n";
        try {
            $indexer = new Indexer($basePath);
            $index = $indexer->load();
            $collectionNames = $index['meta']['collections'] ?? [];
            if (!empty($collectionNames)) {
                $lines[] = "| Collection | Entries |";
                $lines[] = "|------------|---------|";
                foreach ($collectionNames as $name) {
                    $count = count($index['indices']['by_collection'][$name] ?? []);
                    $lines[] = "| {$name} | {$count} |";
                }
                $lines[] = "";
            } else {
                $lines[] = "No collections found. Run `rakun index:rebuild` first.\n";
            }
        } catch (\Throwable) {
            $lines[] = "Unable to load content index.\n";
        }

        // Templates
        $lines[] = "## Templates\n";
        $templateTool = new ListTemplatesTool($basePath);
        $templateResult = $templateTool->execute([]);
        $templates = $templateResult['templates'] ?? [];
        if (!empty($templates)) {
            foreach ($templates as $tpl) {
                $extra = '';
                if (!empty($tpl['extends'])) {
                    $extra = " (extends: {$tpl['extends']})";
                }
                $lines[] = "- `{$tpl['path']}`{$extra}";
            }
            $lines[] = "";
        }

        // Components
        $lines[] = "## Components\n";
        $componentTool = new ListComponentsTool($basePath);
        $componentResult = $componentTool->execute([]);
        $components = $componentResult['components'] ?? [];
        if (!empty($components)) {
            foreach ($components as $comp) {
                $props = !empty($comp['properties']) ? implode(', ', $comp['properties']) : 'none';
                $lines[] = "- **{$comp['name']}** — props: {$props}";
            }
            $lines[] = "";
        }

        // CLI commands
        $lines[] = "## CLI Commands\n";
        $lines[] = "```bash";
        $lines[] = "php rakun serve          # Development server";
        $lines[] = "php rakun index:rebuild   # Rebuild content index";
        $lines[] = "php rakun cache:clear     # Clear all caches";
        $lines[] = "php rakun make:component  # Generate Yoyo component";
        $lines[] = "php rakun make:collection # Generate collection scaffold";
        $lines[] = "php rakun mcp:serve       # Start MCP server for AI";
        $lines[] = "```\n";

        // Conventions
        $lines[] = "## Conventions\n";
        $lines[] = "- Content lives as Markdown files with YAML frontmatter in `content/`";
        $lines[] = "- Templates are Twig files in `templates/`";
        $lines[] = "- Reactive components use Yoyo (htmx-based, server-rendered)";
        $lines[] = "- Configuration in `config/rakun.yaml`";
        $lines[] = "- No database — filesystem is the source of truth";
        $lines[] = "- Run `php rakun index:rebuild` after adding/modifying content files";
        $lines[] = "";

        return implode("\n", $lines);
    }

    /**
     * @return array<string, mixed>
     */
    private function generateMcpJson(): array
    {
        return [
            'mcpServers' => [
                'rakuncms' => [
                    'command' => 'php',
                    'args' => ['rakun', 'mcp:serve'],
                ],
            ],
        ];
    }

    private function findBasePath(): string
    {
        try {
            return \app('base_path');
        } catch (\Throwable) {
        }

        return getcwd() ?: dirname(__DIR__, 3);
    }
}
