<?php

declare(strict_types=1);

namespace Rkn\Cms\Cli;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name: 'herd:install', description: 'Install the RakunCMS Valet driver for Laravel Herd')]
final class HerdInstallCommand extends Command
{
    protected function configure(): void
    {
        $this->addOption('local', null, InputOption::VALUE_NONE, 'Install as LocalValetDriver.php in the project root');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        if ($input->getOption('local')) {
            return $this->installLocal($output);
        }

        return $this->installGlobal($output);
    }

    private function installGlobal(OutputInterface $output): int
    {
        $herdDriversDir = $this->getHerdDriversDir();

        if (!is_dir($herdDriversDir)) {
            $output->writeln('<error>Herd drivers directory not found.</error>');
            $output->writeln('Expected: ' . $herdDriversDir);
            $output->writeln('Make sure Laravel Herd is installed on this machine.');
            return Command::FAILURE;
        }

        $source = $this->getDriverSourcePath();
        $destination = $herdDriversDir . '/RakunCmsValetDriver.php';

        $content = file_get_contents($source);
        if ($content === false) {
            $output->writeln('<error>Could not read driver source file.</error>');
            return Command::FAILURE;
        }

        file_put_contents($destination, $content);

        $output->writeln('<info>RakunCMS Herd driver installed globally.</info>');
        $output->writeln('  Installed to: ' . $destination);
        $output->writeln('');
        $output->writeln('Next steps:');
        $output->writeln('  1. Park your sites directory: <comment>herd park</comment>');
        $output->writeln('  2. Visit <comment>http://your-site.test</comment> in your browser');

        return Command::SUCCESS;
    }

    private function installLocal(OutputInterface $output): int
    {
        $basePath = $this->findBasePath();
        $destination = $basePath . '/LocalValetDriver.php';

        $content = $this->generateLocalDriver();
        file_put_contents($destination, $content);

        $output->writeln('<info>LocalValetDriver.php installed in project root.</info>');
        $output->writeln('  Installed to: ' . $destination);
        $output->writeln('');
        $output->writeln('Next steps:');
        $output->writeln('  1. Link the site: <comment>herd link</comment>');
        $output->writeln('  2. Visit <comment>http://your-site.test</comment> in your browser');

        return Command::SUCCESS;
    }

    private function generateLocalDriver(): string
    {
        return <<<'PHP'
<?php

/**
 * Local Valet/Herd driver for this RakunCMS project.
 * Generated by: php rakun herd:install --local
 */
class LocalValetDriver extends LaravelValetDriver
{
    public function serves(string $sitePath, string $siteName, string $uri): bool
    {
        return true;
    }

    public function isStaticFile(string $sitePath, string $siteName, string $uri): string|false
    {
        $staticPath = $sitePath . '/public' . $uri;

        if (is_file($staticPath)) {
            return $staticPath;
        }

        return false;
    }

    public function frontControllerPath(string $sitePath, string $siteName, string $uri): string
    {
        return $sitePath . '/public/index.php';
    }
}
PHP;
    }

    private function getDriverSourcePath(): string
    {
        return dirname(__DIR__) . '/Herd/RakunCmsValetDriver.php';
    }

    private function getHerdDriversDir(): string
    {
        $home = $_SERVER['HOME'] ?? $_SERVER['USERPROFILE'] ?? '';

        return $home . '/Library/Application Support/Herd/config/valet/Drivers';
    }

    private function findBasePath(): string
    {
        try {
            return \app('base_path');
        } catch (\Throwable) {
        }

        return getcwd() ?: dirname(__DIR__, 3);
    }
}
